version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecommerce-api
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: ecommerce-webapp
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - api
