name: CI for API and WebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api:
    name: API – Install, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      - name: Run tests
        run: npm test
        working-directory: ./api

  webapp:
    name: WebApp – Install, Test, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./webapp

      - name: Run tests
        run: npm test --if-present
        working-directory: ./webapp

      - name: Build the app
        run: npm run build
        working-directory: ./webapp
